//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C192_168_1_TWQ_商家資料庫_dbo_測試商店視圖
    {
        public string NewebSales { get; set; }
        public string CustName_EnCode { get; set; }
        public int No { get; set; }
        public string MerNo_T { get; set; }
        public string CustName { get; set; }
        public string CooperMode { get; set; }
        public string MerState { get; set; }
        public string MerType { get; set; }
        public string HostID { get; set; }
        public Nullable<System.DateTime> Test_Ntc_Date { get; set; }
        public Nullable<System.DateTime> Test_Cmp_Date { get; set; }
        public Nullable<bool> Auth { get; set; }
        public Nullable<bool> InspectStatus { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> IS_IM { get; set; }
        public Nullable<bool> IS_CTID { get; set; }
        public Nullable<bool> OnlyTest { get; set; }
        public Nullable<System.DateTime> TestDelDate { get; set; }
        public string TestPassword { get; set; }
        public Nullable<System.DateTime> OnNtcTime { get; set; }
        public Nullable<System.DateTime> OffNtcTime { get; set; }
    }
}
