//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C192_168_1_TWQ_商家資料庫_dbo_正式商店設定資料
    {
        public int No { get; set; }
        public string MerNo_F { get; set; }
        public string MerNo_T { get; set; }
        public string CustName { get; set; }
        public string MerName_En { get; set; }
        public string MerName_Ch { get; set; }
        public string Account { get; set; }
        public string PassWord { get; set; }
        public string New_PassWord { get; set; }
        public string CooperMode { get; set; }
        public string MID { get; set; }
        public string TID { get; set; }
        public string CMID { get; set; }
        public string CTID { get; set; }
        public string Mall_ID { get; set; }
        public string Org_ID { get; set; }
        public string HostID { get; set; }
        public string BankMode { get; set; }
        public string MerState { get; set; }
        public string MerType2 { get; set; }
        public string OnRemarks { get; set; }
        public string BatchType_N { get; set; }
        public Nullable<System.DateTime> OnNtcTime { get; set; }
        public Nullable<System.DateTime> OnCmpTime { get; set; }
        public Nullable<System.DateTime> OffNtcTime { get; set; }
        public Nullable<System.DateTime> OffCmpTime { get; set; }
        public string OffRemarks { get; set; }
        public string ObjVer_N { get; set; }
        public string ReportMail { get; set; }
        public Nullable<bool> VBV { get; set; }
        public string MerNo_New { get; set; }
        public Nullable<bool> RSP_CardNo { get; set; }
        public Nullable<System.DateTime> SysOn_TimeSt { get; set; }
        public Nullable<System.DateTime> SysOff_TimeSt { get; set; }
        public Nullable<double> Total_Rate { get; set; }
        public Nullable<double> Bank_Rate { get; set; }
        public Nullable<double> Neweb_Rate { get; set; }
        public Nullable<double> Mall_Rate { get; set; }
        public string RateExp { get; set; }
        public string BusinessItem { get; set; }
        public string OnLineCs { get; set; }
        public string OffLineCs { get; set; }
        public Nullable<bool> IS_IM { get; set; }
        public Nullable<bool> IS_CTID { get; set; }
        public string RPCCMerNo { get; set; }
        public string MallType { get; set; }
        public string MallTypeNote { get; set; }
        public Nullable<double> IMRate_3 { get; set; }
        public Nullable<double> IMRate_6 { get; set; }
        public Nullable<double> IMRate_9 { get; set; }
        public Nullable<double> IMRate_12 { get; set; }
        public Nullable<double> IMRate_18 { get; set; }
        public Nullable<double> IMRate_24 { get; set; }
        public Nullable<double> IMRate_36 { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string MerType { get; set; }
        public string AcquireBank { get; set; }
        public string AcquireMode { get; set; }
        public string SettleCycle { get; set; }
        public Nullable<bool> IS_RPRecCCNo { get; set; }
        public Nullable<bool> IS_RPFirstCap { get; set; }
        public Nullable<bool> IS_RPAutoDelFail { get; set; }
        public string HostIPs { get; set; }
        public string AdminIPs { get; set; }
        public string RPUploadIPs { get; set; }
        public string AutoSettleTime { get; set; }
        public Nullable<int> ReportGiven { get; set; }
        public string AsyncTxtNoteURL { get; set; }
        public string MerLogo { get; set; }
        public string MerTxtNote { get; set; }
        public Nullable<int> Mer_Graph { get; set; }
        public string ContraNo { get; set; }
        public Nullable<int> SinSerChar { get; set; }
        public string FrontHostID { get; set; }
        public string MerNo_Old { get; set; }
    }
}
