//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C192_168_1_TWQ_商家資料庫_dbo__合約資料
    {
        public int No { get; set; }
        public string CustName { get; set; }
        public string ContraNo { get; set; }
        public string ContraYear { get; set; }
        public string MallType { get; set; }
        public string ContraState { get; set; }
        public string ServiceType { get; set; }
        public Nullable<System.DateTime> ContraEntDate { get; set; }
        public Nullable<System.DateTime> ContraSendDate { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public Nullable<int> Rent { get; set; }
        public Nullable<int> EarMoney { get; set; }
        public Nullable<System.DateTime> ContraSignDate { get; set; }
        public Nullable<System.DateTime> Contra_IniDate { get; set; }
        public Nullable<short> Contra_ValDate { get; set; }
        public Nullable<System.DateTime> Contra_ExpDate { get; set; }
        public Nullable<System.DateTime> ContraStopDate { get; set; }
        public Nullable<double> Total_Rate { get; set; }
        public Nullable<double> Bank_Rate { get; set; }
        public Nullable<double> Neweb_Rate { get; set; }
        public Nullable<double> Mall_Rate { get; set; }
        public string RentExp { get; set; }
        public string RateExp { get; set; }
        public string NewebSales { get; set; }
        public string Distributor { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string SinSerChar { get; set; }
        public Nullable<bool> IM { get; set; }
        public Nullable<bool> RP { get; set; }
        public Nullable<bool> FAX { get; set; }
    }
}
