//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C192_168_1_TWQ_商家資料庫_dbo_AUTHORITY_FUNCTION
    {
        public int Num { get; set; }
        public string 業務部門系統主表單 { get; set; }
        public string 篩選客戶資料 { get; set; }
        public string 篩選合約資料 { get; set; }
        public string 篩選正式商店資料 { get; set; }
        public string 維護客戶資料 { get; set; }
        public string 維護合約資料 { get; set; }
        public string 維護正式商店資料 { get; set; }
        public string 測試商店資料維護 { get; set; }
        public string 帳務發票寄送標籤選項 { get; set; }
        public string 風管登錄問題交易維護 { get; set; }
        public string 風管詳細登錄問題交易 { get; set; }
        public string 客服FAQ { get; set; }
        public string 業務進階查詢_正式商店 { get; set; }
        public string 業務進階查詢_合約資料 { get; set; }
        public string 測試商店進階查詢 { get; set; }
        public string 合作單位資料篩選 { get; set; }
        public string 維護合約詳細資料New { get; set; }
    }
}
