//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C192_168_1_TWQ_商家資料庫_dbo_FAQ_CS
    {
        public int FAQ_No { get; set; }
        public string QueType { get; set; }
        public string QueSubject { get; set; }
        public string Phenomenon { get; set; }
        public string Confirmation { get; set; }
        public string Suggestion { get; set; }
        public string Cause { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Udated { get; set; }
        public string Creator { get; set; }
        public string Reviser { get; set; }
        public Nullable<int> QueCount { get; set; }
        public Nullable<int> UpdateCount { get; set; }
    }
}
