//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C192_168_1_TWQ_商家資料庫_dbo_客戶基本資料
    {
        public int No { get; set; }
        public string CustName { get; set; }
        public string CustName_En { get; set; }
        public string BusinessNo { get; set; }
        public string CustName_Extn { get; set; }
        public string CustName_Rept { get; set; }
        public string CustName_Bill { get; set; }
        public string AcctTitle { get; set; }
        public string AcctNum { get; set; }
        public string AcctBank { get; set; }
        public string BankBranch { get; set; }
        public string InvAddress { get; set; }
        public string CustTel { get; set; }
        public string CustFax { get; set; }
        public string CustURL { get; set; }
        public string MerURL { get; set; }
        public string FileNo { get; set; }
        public Nullable<long> Capital { get; set; }
        public string Director { get; set; }
        public string DirectorID { get; set; }
        public string AuthPerson { get; set; }
        public string AuthMail { get; set; }
        public string AuthTel { get; set; }
        public string NewebSales { get; set; }
        public string CustAdrs { get; set; }
        public string CustName_EnCode { get; set; }
        public string AddresseeName { get; set; }
        public string InvZipcode { get; set; }
        public string CustZipcode { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IS_Distributor { get; set; }
        public Nullable<bool> InspectStatus { get; set; }
        public string ProjectRecord { get; set; }
    }
}
