//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRA_RENEW
    {
        public int No { get; set; }
        public Nullable<int> ContraCorreCode { get; set; }
        public Nullable<System.DateTime> Contra_IniDate { get; set; }
        public Nullable<short> Contra_ValDate { get; set; }
        public Nullable<System.DateTime> Contra_ExpDate { get; set; }
        public string SignSales { get; set; }
        public string Rent { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public string RentExp { get; set; }
    
        public virtual 合約資料 合約資料 { get; set; }
    }
}
