//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ezPay代收代付
    {
        public string 商家編號 { get; set; }
        public string 商家名稱 { get; set; }
        public string 英文名稱 { get; set; }
        public string 帳號 { get; set; }
        public string 密碼 { get; set; }
        public string 商家型態 { get; set; }
        public bool 通知否 { get; set; }
        public Nullable<System.DateTime> 上線日期 { get; set; }
        public string 傳真號碼 { get; set; }
        public string 客服聯絡人1 { get; set; }
        public string 客服電話1 { get; set; }
        public string 客服依媚兒1 { get; set; }
        public string 客服聯絡人2 { get; set; }
        public string 客服電話2 { get; set; }
        public string 客服依媚兒2 { get; set; }
        public string 客服聯絡人3 { get; set; }
        public string 客服電話3 { get; set; }
        public string 客服依媚兒3 { get; set; }
        public string 會計聯絡人 { get; set; }
        public string 會計電話 { get; set; }
        public string 會計依媚兒 { get; set; }
        public string 撥款週期 { get; set; }
        public string 商家區隔 { get; set; }
        public string 代收費率 { get; set; }
        public string 業務 { get; set; }
        public Nullable<System.DateTime> 下線日期 { get; set; }
        public string 商品 { get; set; }
    }
}
