//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDB2Entities : DbContext
    {
        public TestDB2Entities()
            : base("name=TestDB2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_AUTO_SETTLE_TIME> C_AUTO_SETTLE_TIME { get; set; }
        public virtual DbSet<C_MER_TYPE> C_MER_TYPE { get; set; }
        public virtual DbSet<C_合約狀態> C_合約狀態 { get; set; }
        public virtual DbSet<C_合約資料> C_合約資料 { get; set; }
        public virtual DbSet<C_服務型態> C_服務型態 { get; set; }
        public virtual DbSet<ACQUIRE_BANK> ACQUIRE_BANK { get; set; }
        public virtual DbSet<ACQUIRE_MODE> ACQUIRE_MODE { get; set; }
        public virtual DbSet<ADV_FUNC> ADV_FUNC { get; set; }
        public virtual DbSet<Alipay_Product> Alipay_Product { get; set; }
        public virtual DbSet<AUTHORITY_FUNCTION> AUTHORITY_FUNCTION { get; set; }
        public virtual DbSet<AUTHORITY_SETTLEMENT> AUTHORITY_SETTLEMENT { get; set; }
        public virtual DbSet<AUTO_SERIAL_NUM> AUTO_SERIAL_NUM { get; set; }
        public virtual DbSet<AUTO_SETTLE_TIME> AUTO_SETTLE_TIME { get; set; }
        public virtual DbSet<BANK_BRANCH_CODE> BANK_BRANCH_CODE { get; set; }
        public virtual DbSet<BANK_HQ> BANK_HQ { get; set; }
        public virtual DbSet<BANK_MODE> BANK_MODE { get; set; }
        public virtual DbSet<BATCH_TYPE> BATCH_TYPE { get; set; }
        public virtual DbSet<CONT_ENAB_FUNC> CONT_ENAB_FUNC { get; set; }
        public virtual DbSet<CONT_ENAB_FUNC_TEMP> CONT_ENAB_FUNC_TEMP { get; set; }
        public virtual DbSet<CONTRA_CAUSE> CONTRA_CAUSE { get; set; }
        public virtual DbSet<CONTRA_KIND> CONTRA_KIND { get; set; }
        public virtual DbSet<CONTRA_RENEW> CONTRA_RENEW { get; set; }
        public virtual DbSet<CONTRA_STATE> CONTRA_STATE { get; set; }
        public virtual DbSet<CONTRA_UPDATE> CONTRA_UPDATE { get; set; }
        public virtual DbSet<COOP_MODE> COOP_MODE { get; set; }
        public virtual DbSet<COOP_UNIT> COOP_UNIT { get; set; }
        public virtual DbSet<COOP_UNIT_CONNECT> COOP_UNIT_CONNECT { get; set; }
        public virtual DbSet<DISTRIBUTOR_LIST> DISTRIBUTOR_LIST { get; set; }
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<FAQ_CLASS_CS> FAQ_CLASS_CS { get; set; }
        public virtual DbSet<FAQ_CS> FAQ_CS { get; set; }
        public virtual DbSet<FAQ_QUE_RECORD> FAQ_QUE_RECORD { get; set; }
        public virtual DbSet<FAQ_RELATIVE_LINK> FAQ_RELATIVE_LINK { get; set; }
        public virtual DbSet<FAQ_UPDATE_COUNT> FAQ_UPDATE_COUNT { get; set; }
        public virtual DbSet<HOSTS> HOSTS { get; set; }
        public virtual DbSet<MALL_TYPE> MALL_TYPE { get; set; }
        public virtual DbSet<MER_STATE> MER_STATE { get; set; }
        public virtual DbSet<MER_TX_BATCH> MER_TX_BATCH { get; set; }
        public virtual DbSet<MER_TX_BATCH_TEMP> MER_TX_BATCH_TEMP { get; set; }
        public virtual DbSet<MER_TX_BATCH_TEMP_BLOCK> MER_TX_BATCH_TEMP_BLOCK { get; set; }
        public virtual DbSet<MER_TYPE> MER_TYPE { get; set; }
        public virtual DbSet<MPOS_TID> MPOS_TID { get; set; }
        public virtual DbSet<OBJ_VER> OBJ_VER { get; set; }
        public virtual DbSet<OnCmpData> OnCmpData { get; set; }
        public virtual DbSet<RM_LOGIN_QUESTION_TRADE> RM_LOGIN_QUESTION_TRADE { get; set; }
        public virtual DbSet<RM_NOTICE_UNIT> RM_NOTICE_UNIT { get; set; }
        public virtual DbSet<RM_REGISTER_QUERY_TEMP> RM_REGISTER_QUERY_TEMP { get; set; }
        public virtual DbSet<RM_REGISTER_REASON> RM_REGISTER_REASON { get; set; }
        public virtual DbSet<RM_REGISTER_REASON_CODE> RM_REGISTER_REASON_CODE { get; set; }
        public virtual DbSet<RM_REGISTER_REASON_TEMP> RM_REGISTER_REASON_TEMP { get; set; }
        public virtual DbSet<SERVER_NAME> SERVER_NAME { get; set; }
        public virtual DbSet<SERVICE_TYPE> SERVICE_TYPE { get; set; }
        public virtual DbSet<SETTLE_CYCLE> SETTLE_CYCLE { get; set; }
        public virtual DbSet<SETTLE_IP> SETTLE_IP { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TEMP_ADVANCE_QUERY> TEMP_ADVANCE_QUERY { get; set; }
        public virtual DbSet<TEMP_ADVANCE_QUERY_STORE> TEMP_ADVANCE_QUERY_STORE { get; set; }
        public virtual DbSet<TEMP_SELECT_EMAIL> TEMP_SELECT_EMAIL { get; set; }
        public virtual DbSet<TRADE_STATISTICAL> TRADE_STATISTICAL { get; set; }
        public virtual DbSet<正式商店設定資料> 正式商店設定資料 { get; set; }
        public virtual DbSet<合約資料> 合約資料 { get; set; }
        public virtual DbSet<客戶技術窗口資料> 客戶技術窗口資料 { get; set; }
        public virtual DbSet<客戶客服窗口資料> 客戶客服窗口資料 { get; set; }
        public virtual DbSet<客戶基本資料> 客戶基本資料 { get; set; }
        public virtual DbSet<客戶帳務窗口資料> 客戶帳務窗口資料 { get; set; }
        public virtual DbSet<客戶報表窗口資料> 客戶報表窗口資料 { get; set; }
        public virtual DbSet<客戶業務窗口資料> 客戶業務窗口資料 { get; set; }
        public virtual DbSet<停用連線服務原因> 停用連線服務原因 { get; set; }
        public virtual DbSet<國內發卡銀行> 國內發卡銀行 { get; set; }
        public virtual DbSet<測式商店設定資料> 測式商店設定資料 { get; set; }
        public virtual DbSet<測試商店備註欄> 測試商店備註欄 { get; set; }
        public virtual DbSet<測試商店備註欄暫存> 測試商店備註欄暫存 { get; set; }
        public virtual DbSet<測試商店進階查詢暫存> 測試商店進階查詢暫存 { get; set; }
        public virtual DbSet<C_CASHSYS> C_CASHSYS { get; set; }
        public virtual DbSet<ezPay代收代付> ezPay代收代付 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo__AUTO_SETTLE_TIME> C192_168_1_TWQ_商家資料庫_dbo__AUTO_SETTLE_TIME { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo__MER_TYPE> C192_168_1_TWQ_商家資料庫_dbo__MER_TYPE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo__合約狀態> C192_168_1_TWQ_商家資料庫_dbo__合約狀態 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo__合約資料> C192_168_1_TWQ_商家資料庫_dbo__合約資料 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo__服務型態> C192_168_1_TWQ_商家資料庫_dbo__服務型態 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_ACQUIRE_BANK> C192_168_1_TWQ_商家資料庫_dbo_ACQUIRE_BANK { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_ACQUIRE_MODE> C192_168_1_TWQ_商家資料庫_dbo_ACQUIRE_MODE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_ADV_FUNC> C192_168_1_TWQ_商家資料庫_dbo_ADV_FUNC { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_AUTHORITY_FUNCTION> C192_168_1_TWQ_商家資料庫_dbo_AUTHORITY_FUNCTION { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_AUTHORITY_SETTLEMENT> C192_168_1_TWQ_商家資料庫_dbo_AUTHORITY_SETTLEMENT { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_AUTO_SERIAL_NUM> C192_168_1_TWQ_商家資料庫_dbo_AUTO_SERIAL_NUM { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_AUTO_SETTLE_TIME> C192_168_1_TWQ_商家資料庫_dbo_AUTO_SETTLE_TIME { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_BANK_BRANCH_CODE> C192_168_1_TWQ_商家資料庫_dbo_BANK_BRANCH_CODE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_BANK_HQ> C192_168_1_TWQ_商家資料庫_dbo_BANK_HQ { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_BANK_MODE> C192_168_1_TWQ_商家資料庫_dbo_BANK_MODE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_BATCH_TYPE> C192_168_1_TWQ_商家資料庫_dbo_BATCH_TYPE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_CONT_ENAB_FUNC> C192_168_1_TWQ_商家資料庫_dbo_CONT_ENAB_FUNC { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_CONT_ENAB_FUNC_TEMP> C192_168_1_TWQ_商家資料庫_dbo_CONT_ENAB_FUNC_TEMP { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_CONTRA_CAUSE> C192_168_1_TWQ_商家資料庫_dbo_CONTRA_CAUSE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_CONTRA_KIND> C192_168_1_TWQ_商家資料庫_dbo_CONTRA_KIND { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_CONTRA_RENEW> C192_168_1_TWQ_商家資料庫_dbo_CONTRA_RENEW { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_CONTRA_STATE> C192_168_1_TWQ_商家資料庫_dbo_CONTRA_STATE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_CONTRA_UPDATE> C192_168_1_TWQ_商家資料庫_dbo_CONTRA_UPDATE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_COOP_MODE> C192_168_1_TWQ_商家資料庫_dbo_COOP_MODE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_COOP_UNIT> C192_168_1_TWQ_商家資料庫_dbo_COOP_UNIT { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_COOP_UNIT_CONNECT> C192_168_1_TWQ_商家資料庫_dbo_COOP_UNIT_CONNECT { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_DISTRIBUTOR_LIST> C192_168_1_TWQ_商家資料庫_dbo_DISTRIBUTOR_LIST { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_EMAIL_AUTH> C192_168_1_TWQ_商家資料庫_dbo_EMAIL_AUTH { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_EMPLOYEE> C192_168_1_TWQ_商家資料庫_dbo_EMPLOYEE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_ezPay代收代付> C192_168_1_TWQ_商家資料庫_dbo_ezPay代收代付 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_FAQ_CLASS_CS> C192_168_1_TWQ_商家資料庫_dbo_FAQ_CLASS_CS { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_FAQ_CS> C192_168_1_TWQ_商家資料庫_dbo_FAQ_CS { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_FAQ_QUE_RECORD> C192_168_1_TWQ_商家資料庫_dbo_FAQ_QUE_RECORD { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_FAQ_RELATIVE_LINK> C192_168_1_TWQ_商家資料庫_dbo_FAQ_RELATIVE_LINK { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_FAQ_UPDATE_COUNT> C192_168_1_TWQ_商家資料庫_dbo_FAQ_UPDATE_COUNT { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_HOSTS> C192_168_1_TWQ_商家資料庫_dbo_HOSTS { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_MALL_TYPE> C192_168_1_TWQ_商家資料庫_dbo_MALL_TYPE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_MER_STATE> C192_168_1_TWQ_商家資料庫_dbo_MER_STATE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_MER_TX_BATCH> C192_168_1_TWQ_商家資料庫_dbo_MER_TX_BATCH { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_MER_TX_BATCH_TEMP> C192_168_1_TWQ_商家資料庫_dbo_MER_TX_BATCH_TEMP { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_MER_TX_BATCH_TEMP_BLOCK> C192_168_1_TWQ_商家資料庫_dbo_MER_TX_BATCH_TEMP_BLOCK { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_MER_TYPE> C192_168_1_TWQ_商家資料庫_dbo_MER_TYPE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_OBJ_VER> C192_168_1_TWQ_商家資料庫_dbo_OBJ_VER { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_RM_LOGIN_QUESTION_TRADE> C192_168_1_TWQ_商家資料庫_dbo_RM_LOGIN_QUESTION_TRADE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_RM_NOTICE_UNIT> C192_168_1_TWQ_商家資料庫_dbo_RM_NOTICE_UNIT { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_RM_REGISTER_QUERY_TEMP> C192_168_1_TWQ_商家資料庫_dbo_RM_REGISTER_QUERY_TEMP { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_RM_REGISTER_REASON> C192_168_1_TWQ_商家資料庫_dbo_RM_REGISTER_REASON { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_RM_REGISTER_REASON_CODE> C192_168_1_TWQ_商家資料庫_dbo_RM_REGISTER_REASON_CODE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_RM_REGISTER_REASON_TEMP> C192_168_1_TWQ_商家資料庫_dbo_RM_REGISTER_REASON_TEMP { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_SERVER_NAME> C192_168_1_TWQ_商家資料庫_dbo_SERVER_NAME { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_SERVICE_TYPE> C192_168_1_TWQ_商家資料庫_dbo_SERVICE_TYPE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_SETTLE_CYCLE> C192_168_1_TWQ_商家資料庫_dbo_SETTLE_CYCLE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_SETTLE_IP> C192_168_1_TWQ_商家資料庫_dbo_SETTLE_IP { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_TEMP_ADVANCE_QUERY> C192_168_1_TWQ_商家資料庫_dbo_TEMP_ADVANCE_QUERY { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_TEMP_ADVANCE_QUERY_STORE> C192_168_1_TWQ_商家資料庫_dbo_TEMP_ADVANCE_QUERY_STORE { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_TEMP_SELECT_EMAIL> C192_168_1_TWQ_商家資料庫_dbo_TEMP_SELECT_EMAIL { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_TRADE_STATISTICAL> C192_168_1_TWQ_商家資料庫_dbo_TRADE_STATISTICAL { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_正式商店設定資料> C192_168_1_TWQ_商家資料庫_dbo_正式商店設定資料 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_正式商店標籤視圖> C192_168_1_TWQ_商家資料庫_dbo_正式商店標籤視圖 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_合約資料> C192_168_1_TWQ_商家資料庫_dbo_合約資料 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_合約資料標籤視圖> C192_168_1_TWQ_商家資料庫_dbo_合約資料標籤視圖 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_客戶技術窗口資料> C192_168_1_TWQ_商家資料庫_dbo_客戶技術窗口資料 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_客戶客服窗口資料> C192_168_1_TWQ_商家資料庫_dbo_客戶客服窗口資料 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_客戶基本資料> C192_168_1_TWQ_商家資料庫_dbo_客戶基本資料 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_客戶帳務窗口資料> C192_168_1_TWQ_商家資料庫_dbo_客戶帳務窗口資料 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_客戶報表窗口資料> C192_168_1_TWQ_商家資料庫_dbo_客戶報表窗口資料 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_客戶業務窗口資料> C192_168_1_TWQ_商家資料庫_dbo_客戶業務窗口資料 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_停用連線服務原因> C192_168_1_TWQ_商家資料庫_dbo_停用連線服務原因 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_國內發卡銀行> C192_168_1_TWQ_商家資料庫_dbo_國內發卡銀行 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_測式商店設定資料> C192_168_1_TWQ_商家資料庫_dbo_測式商店設定資料 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_測試商店備註欄> C192_168_1_TWQ_商家資料庫_dbo_測試商店備註欄 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_測試商店備註欄暫存> C192_168_1_TWQ_商家資料庫_dbo_測試商店備註欄暫存 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_測試商店視圖> C192_168_1_TWQ_商家資料庫_dbo_測試商店視圖 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_測試商店進階查詢暫存> C192_168_1_TWQ_商家資料庫_dbo_測試商店進階查詢暫存 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_登錄問題交易主選單視圖> C192_168_1_TWQ_商家資料庫_dbo_登錄問題交易主選單視圖 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_登錄問題交易視圖> C192_168_1_TWQ_商家資料庫_dbo_登錄問題交易視圖 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_登錄問題交易匯出視圖> C192_168_1_TWQ_商家資料庫_dbo_登錄問題交易匯出視圖 { get; set; }
        public virtual DbSet<C192_168_1_TWQ_商家資料庫_dbo_登錄問題原因視圖> C192_168_1_TWQ_商家資料庫_dbo_登錄問題原因視圖 { get; set; }
        public virtual DbSet<EMAIL_AUTH> EMAIL_AUTH { get; set; }
        public virtual DbSet<MPOS視圖> MPOS視圖 { get; set; }
        public virtual DbSet<正式商店標籤視圖> 正式商店標籤視圖 { get; set; }
        public virtual DbSet<合約資料標籤視圖> 合約資料標籤視圖 { get; set; }
        public virtual DbSet<測試商店視圖> 測試商店視圖 { get; set; }
        public virtual DbSet<登錄問題交易主選單視圖> 登錄問題交易主選單視圖 { get; set; }
        public virtual DbSet<登錄問題交易視圖> 登錄問題交易視圖 { get; set; }
        public virtual DbSet<登錄問題交易匯出視圖> 登錄問題交易匯出視圖 { get; set; }
        public virtual DbSet<登錄問題原因視圖> 登錄問題原因視圖 { get; set; }
    }
}
