//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPOS視圖
    {
        public string CustName_En { get; set; }
        public string BusinessNo { get; set; }
        public string ProjectRecord { get; set; }
        public Nullable<bool> InspectStatus { get; set; }
        public Nullable<bool> IS_Distributor { get; set; }
        public string Remarks { get; set; }
        public string CustZipcode { get; set; }
        public string InvZipcode { get; set; }
        public string AddresseeName { get; set; }
        public string CustName_EnCode { get; set; }
        public string CustAdrs { get; set; }
        public string NewebSales { get; set; }
        public string AuthTel { get; set; }
        public string AuthMail { get; set; }
        public string AuthPerson { get; set; }
        public string DirectorID { get; set; }
        public string InvAddress { get; set; }
        public string CustTel { get; set; }
        public string CustFax { get; set; }
        public string CustURL { get; set; }
        public string MerURL { get; set; }
        public string FileNo { get; set; }
        public Nullable<long> Capital { get; set; }
        public string Director { get; set; }
        public string CustName_Extn { get; set; }
        public string CustName_Bill { get; set; }
        public string CustName_Rept { get; set; }
        public string AcctTitle { get; set; }
        public string AcctNum { get; set; }
        public string AcctBank { get; set; }
        public string BankBranch { get; set; }
        public string MerNo_F { get; set; }
        public string MerNo_T { get; set; }
        public string Expr1 { get; set; }
        public string MerName_En { get; set; }
        public string MerName_Ch { get; set; }
        public string Account { get; set; }
        public string PassWord { get; set; }
        public string New_PassWord { get; set; }
        public string CooperMode { get; set; }
        public string CMID { get; set; }
        public string CTID { get; set; }
        public string Mall_ID { get; set; }
        public string Org_ID { get; set; }
        public string HostID { get; set; }
        public string BankMode { get; set; }
        public string MerState { get; set; }
        public string MerType2 { get; set; }
        public string OnRemarks { get; set; }
        public string BatchType_N { get; set; }
        public Nullable<System.DateTime> OnNtcTime { get; set; }
        public Nullable<System.DateTime> OnCmpTime { get; set; }
        public Nullable<System.DateTime> OffNtcTime { get; set; }
        public Nullable<System.DateTime> OffCmpTime { get; set; }
        public string OffRemarks { get; set; }
        public string ObjVer_N { get; set; }
        public Nullable<bool> VBV { get; set; }
        public string ReportMail { get; set; }
        public string MerNo_New { get; set; }
        public Nullable<bool> RSP_CardNo { get; set; }
        public Nullable<System.DateTime> SysOn_TimeSt { get; set; }
        public Nullable<System.DateTime> SysOff_TimeSt { get; set; }
        public Nullable<double> Total_Rate { get; set; }
        public Nullable<double> Bank_Rate { get; set; }
        public Nullable<double> Neweb_Rate { get; set; }
        public Nullable<double> Mall_Rate { get; set; }
        public string Credit { get; set; }
        public string Credit_Plus { get; set; }
        public string RateExp { get; set; }
        public string BusinessItem { get; set; }
        public string OnLineCs { get; set; }
        public string OffLineCs { get; set; }
        public Nullable<bool> IS_IM { get; set; }
        public Nullable<bool> IS_CTID { get; set; }
        public string RPCCMerNo { get; set; }
        public string MallType { get; set; }
        public string MallTypeNote { get; set; }
        public Nullable<double> IMRate_3 { get; set; }
        public Nullable<double> IMRate_6 { get; set; }
        public Nullable<double> IMRate_9 { get; set; }
        public Nullable<double> IMRate_12 { get; set; }
        public Nullable<double> IMRate_18 { get; set; }
        public Nullable<double> IMRate_24 { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<double> IMRate_36 { get; set; }
        public string MerType { get; set; }
        public string AcquireBank { get; set; }
        public string AcquireMode { get; set; }
        public Nullable<bool> Is_UnionPay { get; set; }
        public string SettleCycle { get; set; }
        public Nullable<bool> IS_RPRecCCNo { get; set; }
        public Nullable<bool> IS_RPFirstCap { get; set; }
        public Nullable<bool> IS_RPAutoDelFail { get; set; }
        public string HostIPs { get; set; }
        public string AdminIPs { get; set; }
        public string RPUploadIPs { get; set; }
        public string AutoSettleTime { get; set; }
        public Nullable<int> ReportGiven { get; set; }
        public string AsyncTxtNoteURL { get; set; }
        public string MerLogo { get; set; }
        public string MerTxtNote { get; set; }
        public Nullable<int> Mer_Graph { get; set; }
        public string ContraNo { get; set; }
        public Nullable<int> SinSerChar { get; set; }
        public string FrontHostID { get; set; }
        public string MerNo_Old { get; set; }
        public Nullable<bool> SMS { get; set; }
        public Nullable<bool> BlackList { get; set; }
        public string CS_VAP { get; set; }
        public string CS_IBON { get; set; }
        public Nullable<bool> CS_VAPCHK { get; set; }
        public string CS_CS { get; set; }
        public Nullable<bool> CS_WEBATMCHK { get; set; }
        public Nullable<bool> CS_IBONCHK { get; set; }
        public Nullable<bool> CS_FAMIPORTCHK { get; set; }
        public Nullable<bool> CS_LIFEETCHK { get; set; }
        public Nullable<bool> CS_OKGOCHK { get; set; }
        public Nullable<bool> CS_ALIPAYCHK { get; set; }
        public Nullable<bool> CS_ALIPAYWAPCHK { get; set; }
        public Nullable<bool> CS_CSCHK { get; set; }
        public string AliFee { get; set; }
        public string AliRatio { get; set; }
        public string AliMallFee { get; set; }
        public string AliMallRatio { get; set; }
        public string Ali_Overtime { get; set; }
        public string AliWap_Fee { get; set; }
        public string AliWap_Ratio { get; set; }
        public string AliWapMall_Fee { get; set; }
        public string AliWapMall_Ratio { get; set; }
        public string AliWap_Overtime { get; set; }
        public Nullable<int> MPOSCorreCode { get; set; }
        public Nullable<bool> Is_Autobilling { get; set; }
        public string Alipay_Product { get; set; }
        public Nullable<bool> P33 { get; set; }
        public string CustName { get; set; }
        public string Machine_No { get; set; }
        public string MID { get; set; }
        public string TID { get; set; }
        public Nullable<System.DateTime> MPOS_OnCmpTime { get; set; }
    }
}
