//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RM_LOGIN_QUESTION_TRADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RM_LOGIN_QUESTION_TRADE()
        {
            this.RM_REGISTER_REASON = new HashSet<RM_REGISTER_REASON>();
        }
    
        public int NumCorrespondingly { get; set; }
        public string MerNo { get; set; }
        public string OrderNum { get; set; }
        public Nullable<int> Amount { get; set; }
        public string AuthCode { get; set; }
        public string CreditCard { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public Nullable<System.DateTime> AuthDate { get; set; }
        public Nullable<bool> IS_Receipt { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
        public Nullable<System.DateTime> DisputeCollectDate { get; set; }
        public Nullable<System.DateTime> DeFundDate { get; set; }
        public string ReasonRemarks { get; set; }
        public string NoticeUnit { get; set; }
    
        public virtual RM_NOTICE_UNIT RM_NOTICE_UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RM_REGISTER_REASON> RM_REGISTER_REASON { get; set; }
    }
}
