//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RM_NOTICE_UNIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RM_NOTICE_UNIT()
        {
            this.RM_LOGIN_QUESTION_TRADE = new HashSet<RM_LOGIN_QUESTION_TRADE>();
        }
    
        public int No { get; set; }
        public string NoticeUnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RM_LOGIN_QUESTION_TRADE> RM_LOGIN_QUESTION_TRADE { get; set; }
    }
}
