//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_ADVANCE_QUERY
    {
        public int No { get; set; }
        public string QueryPerson { get; set; }
        public string ContraKind { get; set; }
        public string ContraNo { get; set; }
        public string ContraYear { get; set; }
        public string ContraMonth { get; set; }
        public string MallType { get; set; }
        public string ServiceType { get; set; }
        public string ContraState { get; set; }
        public string Distributor { get; set; }
        public string ContraEntDate { get; set; }
        public string ContraSendDate { get; set; }
        public string Contra_IniDate { get; set; }
        public string Contra_ExpDate { get; set; }
        public string ContraStopDate { get; set; }
        public string Capital { get; set; }
        public string BusinessNo { get; set; }
        public string NewebSales { get; set; }
        public string NewebSales_C { get; set; }
    }
}
