//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_SELECT_EMAIL
    {
        public int No { get; set; }
        public string MerState { get; set; }
        public string HostID { get; set; }
        public string MerType { get; set; }
        public string MallType { get; set; }
        public string AcquireBank { get; set; }
        public string AcquireMode { get; set; }
        public Nullable<bool> VBV { get; set; }
        public string QueryPerson { get; set; }
    }
}
