//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_ADVANCE_QUERY_STORE
    {
        public int No { get; set; }
        public string QueryPerson { get; set; }
        public string MerNo_F { get; set; }
        public string AcquireMode { get; set; }
        public string AcquireBank { get; set; }
        public string MerType { get; set; }
        public string MallType { get; set; }
        public string SettleCycle { get; set; }
        public string MID { get; set; }
        public string TID { get; set; }
        public string CMID { get; set; }
        public string CTID { get; set; }
        public string BusinessItem { get; set; }
        public Nullable<bool> VBV { get; set; }
        public string Capital { get; set; }
        public string BusinessNo { get; set; }
        public string NewebSales { get; set; }
        public string MerState { get; set; }
        public Nullable<bool> IS_CTID { get; set; }
        public Nullable<bool> IS_IM { get; set; }
        public string OnNtcTime { get; set; }
        public string OffNtcTime { get; set; }
        public string OnLineCs { get; set; }
        public string OffLineCs { get; set; }
        public string HostID { get; set; }
        public string FrontHostID { get; set; }
    }
}
