//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 合約資料
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 合約資料()
        {
            this.CONT_ENAB_FUNC = new HashSet<CONT_ENAB_FUNC>();
            this.CONTRA_RENEW = new HashSet<CONTRA_RENEW>();
            this.CONTRA_UPDATE = new HashSet<CONTRA_UPDATE>();
        }
    
        public int No { get; set; }
        public string CustName { get; set; }
        public string ContraNo { get; set; }
        public string ContraYear { get; set; }
        public string ContraMonth { get; set; }
        public string MallType { get; set; }
        public string ContraState { get; set; }
        public string ServiceType { get; set; }
        public Nullable<System.DateTime> ContraEntDate { get; set; }
        public Nullable<System.DateTime> ContraSendDate { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public string Rent { get; set; }
        public string EarMoney { get; set; }
        public Nullable<System.DateTime> ContraSignDate { get; set; }
        public Nullable<System.DateTime> Contra_IniDate { get; set; }
        public Nullable<short> Contra_ValDate { get; set; }
        public Nullable<System.DateTime> Contra_ExpDate { get; set; }
        public Nullable<System.DateTime> ContraStopDate { get; set; }
        public Nullable<double> Total_Rate { get; set; }
        public Nullable<double> Bank_Rate { get; set; }
        public Nullable<double> Neweb_Rate { get; set; }
        public Nullable<double> Mall_Rate { get; set; }
        public string RentExp { get; set; }
        public string RateExp { get; set; }
        public string NewebSales { get; set; }
        public string Distributor { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string SinSerChar { get; set; }
        public Nullable<bool> IM { get; set; }
        public Nullable<bool> RP { get; set; }
        public Nullable<bool> FAX { get; set; }
        public string ContraKind { get; set; }
        public string ContraNo_Last { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public string AcctTitle { get; set; }
        public string AcctNum { get; set; }
        public string AcctBank { get; set; }
        public string BankBranch { get; set; }
        public string AcquireBank { get; set; }
        public Nullable<bool> Is_MAST { get; set; }
        public string ContraType { get; set; }
        public Nullable<bool> isNewebPay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONT_ENAB_FUNC> CONT_ENAB_FUNC { get; set; }
        public virtual CONTRA_KIND CONTRA_KIND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRA_RENEW> CONTRA_RENEW { get; set; }
        public virtual CONTRA_STATE CONTRA_STATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRA_UPDATE> CONTRA_UPDATE { get; set; }
        public virtual MALL_TYPE MALL_TYPE { get; set; }
        public virtual SERVICE_TYPE SERVICE_TYPE { get; set; }
        public virtual 客戶基本資料 客戶基本資料 { get; set; }
    }
}
