//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客戶客服窗口資料
    {
        public int No { get; set; }
        public string CustName { get; set; }
        public string CsName { get; set; }
        public string CsTel { get; set; }
        public string CsMail { get; set; }
        public string CsIM { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual 客戶基本資料 客戶基本資料 { get; set; }
    }
}
