//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客戶基本資料
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 客戶基本資料()
        {
            this.SETTLE_IP = new HashSet<SETTLE_IP>();
            this.TRADE_STATISTICAL = new HashSet<TRADE_STATISTICAL>();
            this.正式商店設定資料 = new HashSet<正式商店設定資料>();
            this.合約資料 = new HashSet<合約資料>();
            this.客戶技術窗口資料 = new HashSet<客戶技術窗口資料>();
            this.客戶客服窗口資料 = new HashSet<客戶客服窗口資料>();
            this.客戶帳務窗口資料 = new HashSet<客戶帳務窗口資料>();
            this.客戶報表窗口資料 = new HashSet<客戶報表窗口資料>();
            this.客戶業務窗口資料 = new HashSet<客戶業務窗口資料>();
            this.測式商店設定資料 = new HashSet<測式商店設定資料>();
        }
    
        public int No { get; set; }
        public string CustName { get; set; }
        public string CustName_En { get; set; }
        public string BusinessNo { get; set; }
        public string CustName_Extn { get; set; }
        public string CustName_Rept { get; set; }
        public string CustName_Bill { get; set; }
        public string AcctTitle { get; set; }
        public string AcctNum { get; set; }
        public string AcctBank { get; set; }
        public string BankBranch { get; set; }
        public string InvAddress { get; set; }
        public string CustTel { get; set; }
        public string CustFax { get; set; }
        public string CustURL { get; set; }
        public string MerURL { get; set; }
        public string FileNo { get; set; }
        public Nullable<long> Capital { get; set; }
        public string Director { get; set; }
        public string DirectorID { get; set; }
        public string AuthPerson { get; set; }
        public string AuthMail { get; set; }
        public string AuthTel { get; set; }
        public string NewebSales { get; set; }
        public string CustAdrs { get; set; }
        public string CustName_EnCode { get; set; }
        public string AddresseeName { get; set; }
        public string InvZipcode { get; set; }
        public string CustZipcode { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IS_Distributor { get; set; }
        public Nullable<bool> InspectStatus { get; set; }
        public string ProjectRecord { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SETTLE_IP> SETTLE_IP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRADE_STATISTICAL> TRADE_STATISTICAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<正式商店設定資料> 正式商店設定資料 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<合約資料> 合約資料 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶技術窗口資料> 客戶技術窗口資料 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶客服窗口資料> 客戶客服窗口資料 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶帳務窗口資料> 客戶帳務窗口資料 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶報表窗口資料> 客戶報表窗口資料 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶業務窗口資料> 客戶業務窗口資料 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<測式商店設定資料> 測式商店設定資料 { get; set; }
    }
}
