//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 正式商店標籤視圖
    {
        public string CustName { get; set; }
        public string CustZipcode { get; set; }
        public string CustAdrs { get; set; }
        public string SalesName { get; set; }
        public string SalesTel { get; set; }
    }
}
